<?php

/**
 * Creates the People metaboxes. Uses Advanced Custom Fields.
 */

class ALP_Metabox {

	public function __construct() {

		// Register Field Groups
		if(function_exists("register_field_group"))
		{
			register_field_group(array (
				'id' => 'acf_people-fields',
				'title' => 'People Fields',
				'fields' => array (
					array (
						'key' => 'field_52540a7be7804',
						'label' => 'First Name',
						'name' => 'ag-people-first-name',
						'type' => 'text',
						'required' => 1,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_52540aa741c37',
						'label' => 'Last Name',
						'name' => 'ag-people-last-name',
						'type' => 'text',
						'required' => 1,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_52541ab6ce6de',
						'label' => 'Title',
						'name' => 'ag-people-title',
						'type' => 'text',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_52540c3edf97b',
						'label' => 'Photo',
						'name' => 'ag-people-photo',
						'type' => 'image',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_52540abf41c38',
						'label' => 'Office Location',
						'name' => 'ag-people-office-location',
						'type' => 'text',
						'default_value' => '',
						'placeholder' => '102A AGLS',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5272c2754c8fa',
						'label' => 'Resume/CV',
						'name' => 'ag-people-resume',
						'type' => 'file',
						'save_format' => 'url',
						'library' => 'all',
					),
					array (
						'key' => 'field_52540af341c39',
						'label' => 'Email',
						'name' => 'ag-people-email',
						'type' => 'email',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array (
						'key' => 'field_52540b4d41c3a',
						'label' => 'Phone',
						'name' => 'ag-people-phone',
						'type' => 'text',
						'default_value' => '',
						'placeholder' => 'xxx-xxx-xxxx',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_52540b7441c3b',
						'label' => 'Website',
						'name' => 'ag-people-website',
						'type' => 'text',
						'default_value' => '',
						'placeholder' => 'http://agrilife.org',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_52540ba541c3c',
						'label' => 'Undergraduate Education',
						'name' => 'ag-people-undergrad',
						'type' => 'repeater',
						'sub_fields' => array (
							array (
								'key' => 'field_52540bcd41c3d',
								'label' => 'Degree',
								'name' => 'ag-people-undergrad-degree',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Degree',
					),
					array (
						'key' => 'field_52540bf641c3e',
						'label' => 'Graduate Education',
						'name' => 'ag-people-graduate',
						'type' => 'repeater',
						'sub_fields' => array (
							array (
								'key' => 'field_52540bf641c3f',
								'label' => 'Degree',
								'name' => 'ag-people-graduate-degree',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Degree',
					),
					array (
						'key' => 'field_52541865a0bba',
						'label' => 'Courses Taught',
						'name' => 'ag-people-courses',
						'type' => 'repeater',
						'sub_fields' => array (
							array (
								'key' => 'field_52541878a0bbb',
								'label' => 'Course',
								'name' => 'ag-people-course',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Course',
					),
					array (
						'key' => 'field_5254180ea0bb8',
						'label' => 'Awards Received',
						'name' => 'ag-people-awards',
						'type' => 'repeater',
						'sub_fields' => array (
							array (
								'key' => 'field_52541842a0bb9',
								'label' => 'Award',
								'name' => 'ag-people-award',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Award',
					),
					array (
						'key' => 'field_525416b3f2379',
						'label' => 'Content',
						'name' => 'ag-people-content',
						'type' => 'flexible_content',
						'layouts' => array (
							array (
								'label' => 'Header',
								'name' => 'ag-people-content-header',
								'display' => 'row',
								'sub_fields' => array (
									array (
										'key' => 'field_525416d5f237a',
										'label' => 'Header',
										'name' => 'header',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'none',
										'maxlength' => '',
									),
								),
							),
							array (
								'label' => 'Text',
								'name' => 'ag-people-content-text',
								'display' => 'row',
								'sub_fields' => array (
									array (
										'key' => 'field_525416f2f237c',
										'label' => 'Text',
										'name' => 'text',
										'type' => 'wysiwyg',
										'column_width' => '',
										'default_value' => '',
										'toolbar' => 'basic',
										'media_upload' => 'no',
									),
								),
							),
							array (
								'label' => 'Image',
								'name' => 'ag-people-content-image',
								'display' => 'row',
								'sub_fields' => array (
									array (
										'key' => 'field_5254170cf237e',
										'label' => 'Image',
										'name' => 'image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
							),
							array (
								'label' => 'Gallery',
								'name' => 'ag-people-content-gallery',
								'display' => 'row',
								'sub_fields' => array (
									array (
										'key' => 'field_52541732f2380',
										'label' => 'Gallery',
										'name' => 'gallery',
										'type' => 'gallery',
										'column_width' => '',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
							),
						),
						'button_label' => 'Add Section',
					),
				),
				'location' => array (
					array (
						array (
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'people',
							'order_no' => 0,
							'group_no' => 0,
						),
					),
				),
				'options' => array (
					'position' => 'normal',
					'layout' => 'no_box',
					'hide_on_screen' => array (
						0 => 'the_content',
						1 => 'excerpt',
						2 => 'custom_fields',
						3 => 'discussion',
						4 => 'comments',
						5 => 'featured_image',
						6 => 'categories',
						7 => 'tags',
						8 => 'send-trackbacks',
					),
				),
				'menu_order' => 0,
			));
		}


	}

}