<?php

/**
 * Creates the People metaboxes. Uses Advanced Custom Fields.
 */

class ALP_Metabox {

	public function __construct() {

		// Register Field Groups
		if( function_exists('acf_add_local_field_group') ):

			acf_add_local_field_group(array(
				'key' => 'group_5b9bde43a992a',
				'title' => 'People Fields',
				'fields' => array(
					array(
						'key' => 'field_52540a7be7804',
						'label' => 'First Name',
						'name' => 'ag-people-first-name',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array(
						'key' => 'field_52540aa741c37',
						'label' => 'Last Name',
						'name' => 'ag-people-last-name',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array(
						'key' => 'field_52541ab6ce6de',
						'label' => 'Title',
						'name' => 'ag-people-title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array(
						'key' => 'field_52540c3edf97b',
						'label' => 'Photo',
						'name' => 'ag-people-photo',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'return_format' => 'array',
						'min_width' => 0,
						'min_height' => 0,
						'min_size' => 0,
						'max_width' => 0,
						'max_height' => 0,
						'max_size' => 0,
						'mime_types' => '',
					),
					array(
						'key' => 'field_52540abf41c38',
						'label' => 'Office Location',
						'name' => 'ag-people-office-location',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '102A AGLS',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5272c2754c8fa',
						'label' => 'Resume/CV',
						'name' => 'ag-people-resume',
						'type' => 'file',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'library' => 'all',
						'return_format' => 'url',
						'min_size' => 0,
						'max_size' => 0,
						'mime_types' => '',
					),
					array(
						'key' => 'field_52540af341c39',
						'label' => 'Email',
						'name' => 'ag-people-email',
						'type' => 'email',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_52540b4d41c3a',
						'label' => 'Phone',
						'name' => 'ag-people-phone',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'xxx-xxx-xxxx',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array(
						'key' => 'field_52540b7441c3b',
						'label' => 'Website',
						'name' => 'ag-people-website',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'http://agrilife.org',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array(
						'key' => 'field_52540ba541c3c',
						'label' => 'Undergraduate Education',
						'name' => 'ag-people-undergrad',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Degree',
						'min' => 0,
						'max' => 0,
						'collapsed' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_52540bcd41c3d',
								'label' => 'Degree',
								'name' => 'ag-people-undergrad-degree',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
						),
					),
					array(
						'key' => 'field_52540bf641c3e',
						'label' => 'Graduate Education',
						'name' => 'ag-people-graduate',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Degree',
						'min' => 0,
						'max' => 0,
						'collapsed' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_52540bf641c3f',
								'label' => 'Degree',
								'name' => 'ag-people-graduate-degree',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
						),
					),
					array(
						'key' => 'field_52541865a0bba',
						'label' => 'Courses Taught',
						'name' => 'ag-people-courses',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Course',
						'min' => 0,
						'max' => 0,
						'collapsed' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_52541878a0bbb',
								'label' => 'Course',
								'name' => 'ag-people-course',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
						),
					),
					array(
						'key' => 'field_5254180ea0bb8',
						'label' => 'Awards Received',
						'name' => 'ag-people-awards',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Award',
						'min' => 0,
						'max' => 0,
						'collapsed' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_52541842a0bb9',
								'label' => 'Award',
								'name' => 'ag-people-award',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
						),
					),
					array(
						'key' => 'field_525416b3f2379',
						'label' => 'Content',
						'name' => 'ag-people-content',
						'type' => 'flexible_content',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layouts' => array(
							array(
								'key' => '5b9be50643322',
								'name' => 'ag-people-content-header',
								'label' => 'Header',
								'display' => 'row',
								'sub_fields' => array(
									array(
										'key' => 'field_525416d5f237a',
										'label' => 'Header',
										'name' => 'header',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'none',
										'maxlength' => '',
									),
								),
								'min' => '',
								'max' => '',
							),
							array(
								'key' => '5b9be50643344',
								'name' => 'ag-people-content-text',
								'label' => 'Text',
								'display' => 'row',
								'sub_fields' => array(
									array(
										'key' => 'field_525416f2f237c',
										'label' => 'Text',
										'name' => 'text',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'tabs' => 'all',
										'delay' => 0,
									),
								),
								'min' => '',
								'max' => '',
							),
							array(
								'key' => '5b9be50643362',
								'name' => 'ag-people-content-image',
								'label' => 'Image',
								'display' => 'row',
								'sub_fields' => array(
									array(
										'key' => 'field_5254170cf237e',
										'label' => 'Image',
										'name' => 'image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'return_format' => 'array',
										'min_width' => 0,
										'min_height' => 0,
										'min_size' => 0,
										'max_width' => 0,
										'max_height' => 0,
										'max_size' => 0,
										'mime_types' => '',
									),
								),
								'min' => '',
								'max' => '',
							),
							array(
								'key' => '5b9be5064337f',
								'name' => 'ag-people-content-gallery',
								'label' => 'Gallery',
								'display' => 'row',
								'sub_fields' => array(
									array(
										'key' => 'field_52541732f2380',
										'label' => 'Gallery',
										'name' => 'gallery',
										'type' => 'gallery',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'min' => 0,
										'max' => 0,
										'min_width' => 0,
										'min_height' => 0,
										'min_size' => 0,
										'max_width' => 0,
										'max_height' => 0,
										'max_size' => 0,
										'mime_types' => '',
										'insert' => 'append',
									),
								),
								'min' => '',
								'max' => '',
							),
						),
						'button_label' => 'Add Section',
						'min' => '',
						'max' => '',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'people',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'acf_after_title',
				'style' => 'seamless',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'the_content',
					1 => 'excerpt',
					2 => 'discussion',
					3 => 'comments',
					4 => 'featured_image',
					5 => 'categories',
					6 => 'tags',
					7 => 'send-trackbacks',
				),
				'active' => 1,
				'description' => '',
			));

		endif;

	}

}
